server:
  port: 8080

spring:
  application:
    name: credit-agreement-ai
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.db.hackathon: DEBUG

google:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.5-flash

open-router:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.1-flash-lite
