server:
  port: 8080

spring:
  cloud:
    gcp:
      project-id: gen-lang-client-0146388054
  application:
    name: credit-agreement-ai
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: abhijitbalse
#    password:
#    driver-class-name: org.postgresql.Driver
     url: jdbc:h2:mem:hackathon26
     username: sa
     password:
     driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    com.db.hackathon: DEBUG

google:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.5-flash
  document-ai:
    project-id: 277914962735
    location: asia-south1
    processor-id: bbe75eb9ad1a653c
    credentials: hackathon26-credentials.json
  pubsub:
    subscription: agreement-upload-sub
  bucket:
    name: loaniq-agreement

open-router:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.1-flash-lite