server:
  port: 8080

spring:
  cloud:
    gcp:
      project-id: hackathon26-509004
  application:
    name: credit-agreement-ai
  datasource:
     url: jdbc:h2:mem:hackathon26
     username: sa
     password:
     driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    root: INFO
    com.db.hackathon: DEBUG

google:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.5-flash
  document-ai:
    project-id: 825071657292
    location: asia-south1
    processor-id: d014d4c7a89929da
    credentials: hackathon26-credentials.json
  pubsub:
    subscription: credit-agreement-upload-topic-sub
  bucket:
    name: credit_aggrement_bucket

open-router:
  ai:
    appName: credit-agreement-ai
    userId: ops-user
    model: gemini-3.1-flash-lite